language: c

os:
  - linux
  - osx

compiler:
  - gcc
  # will use clang on osx

branches:
  only:
  - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install --upgrade pip ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install lcov ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install valgrind ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install coveralls-lcov ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install cpplint ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cpplint --repository=src/arithmetic/ src/arithmetic/*.c src/arithmetic/*.h test/arithmetic/*.c ; fi
  - mkdir build
  - pushd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. -DBUILD_COVERAGE=1 -DTEST_VALGRIND=1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. ; fi
  - make
  - make test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make coverage  ; fi
  - popd

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls-lcov build/coverage.info  ; fi

