language: c

compiler:
  - gcc

branches:
  only:
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - pip3 install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake .. -DUSE_GCOV=1
  - make
  - make test

after_success:
  - coveralls --root src/

