language: c

compiler:
  - gcc

branches:
  only:
  - master

install:
  - sudo apt-get install lcov
  - gem install coveralls-lcov

before_script:
  - mkdir build
  - cd build
  - lcov --directory . --zerocounters
 
script:
  - cmake .. -DUSE_GCOV=1
  - make
  - make test

after_success:
  - cd ..
  - lcov --directory build/src --capture --output-file coverage.info
  - sed -i 's#'`pwd`'/##g' coverage.info
  - coveralls-lcov coverage.info

