language: c

os:
  - linux
  - osx

compiler:
  - gcc
  # will use clang on osx

branches:

  only:
  - master

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install lcov ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install valgrind ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install coveralls-lcov ; fi
  - pip install --user cpplint

before_script:
  - mkdir build
  - cd build

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. -DBUILD_COVERAGE=1 -DTEST_VALGRIND=1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. ; fi
  - make
  - make test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make coverage  ; fi
  - cpplint --repository=src/arithmetic/ src/arithmetic/*.c src/arithmetic/*.h 

after_success:
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls-lcov build/coverage.info  ; fi
