language: c

compiler:
  - gcc

branches:
  only:
  - master

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake .. -DUSE_GCOV=1
  - make
  - make test

after_success:
  - python3 `which coveralls` --root src/

