language: c

compiler:
  - gcc

branches:
  only:
  - master

install:
  - gem install coveralls-lcov

before_script:
  - lcov --directory . --zerocounters
 
script:
  - mkdir build
  - cd build
  - cmake .. -DUSE_GCOV=1
  - make
  - make test

after_success:
  - cd build
  - lcov --directory src --capture --output-file coverage.info
  - coveralls-lcov coverage.info

