language: c

compiler:
  - gcc

branches:
  only:
  - master

install:
  - sudo apt-get install lcov
  - gem install coveralls-lcov

before_script:
  - mkdir build
  - cd build
 
script:
  - cmake .. -DBUILD_COVERAGE=1 -DBUILD_HTML_COVERAGE=1
  - make
  - make test
  - make coverage

after_success:
  - cd ..
  - coveralls-lcov build/coverage.info

